# Interoperabilidad en la AGE

::: {.callout-note icon="false"}
## 📋 Marco de referencia
- Temas
  - 45. ENI
  - 46. NTI
- Referencias
  - Portal de Administración Electrónica, [Esquema Nacional de Interoperabilidad](https://administracionelectronica.gob.es/pae_Home/pae_Estrategias/pae_Interoperabilidad_Inicio/pae_Esquema_Nacional_de_Interoperabilidad.html), PAe
  - Portal de Administración Electrónica; [Normas técnicas de interoperabilidad](https://administracionelectronica.gob.es/pae_Home/pae_Estrategias/pae_Interoperabilidad_Inicio/pae_Normas_tecnicas_de_interoperabilidad.html); PAe. 
  - Rey Almansa, Gemma del; Dobón Muñoz, Mariam. Tema 43: Interoperabilidad de sistemas (1). El Esquema Nacional de Interoperabilidad. Dimensiones de la interoperabilidad. Astic, 2023.
  - Martín Ortega, Elisa. Tema 44: Interoperabilidad de sistemas (2). Las Normas Técnicas de Interoperabilidad. Interoperabilidad de los documentos y expedientes electrónicos y normas para el intercambio de datos entre Administraciones Públicas. Astic, 2023.
  - [Esquema Nacional de Interoperabilidad](https://runmodule.com/2025/09/11/esquema-nacional-de-interoperabilidad-de-espana/)
:::

## Esquema Nacional de Interoperabilidad

El Esquema Nacional de Interoperabilidad de España se regula a través del [Real Decreto 4/2010](../02-analisis/regulaciones.qmd#BOE-A-2010-1331).

### Niveles del ENI

Niveles del ENI:

- Interoperabilidad jurídica
- Interoperabilidad organizativa
- Interoperabilidad semántica
- Interoperabilidad técnica

### Dimensiones del ENI

Dimensiones del ENI:

- Dimensión legal
- Dimensión organizativa
- Dimensión semántica
- Dimensión técnica

### Instrumentos del ENI

Existen los siguientes inventarios:

- [SIA](serv-comunes.qmd#sia)
- [DIR3](serv-comunes.qmd#dir3)
- CISE
- [CTT](serv-comunes.qmd#ctt)

Los dos primeros (SIA y DIR3) trabajan la dimensión/nivel organizativa (al inventariar procesos y organismos, respectivamente), CISE trata la semántica (al inventariar modelos de datos) y CTT la técnica (al inventariar productos y servicios digitales).

    BOE-A-2010-1331 
## Normas

El ENI está formado por normas.

Algunas normas del ENI:

- Catálogo de estándares.
- Política de Firma Electrónica y de certificados de la Administración.
- Reutilización de recursos de información.

## NTI

Existen múltiples NTIs.

Norma Técnica de Interoperabilidad (NTI):

- Catálogo de estándares
- Documento electrónico
- Digitalización de documentos
- Expediente electrónico
- Política de firma y sellos electrónicos y de certificados de la Administración
- Protocolos de intermediación de datos
- Relación de modelos de datos
- Política de gestión de documentos electrónicos
- Requisitos de conexión a la Red de comunicaciones de las Administraciones Públicas españolas
- Procedimientos de copiado auténtico y conversión entre documentos electrónicos
- Modelo de Datos para el intercambio de asientos entre las Entidades Registrales
- Reutilización de recursos de información
- Norma SICRES (Sistema de Información Común de Registros de Entrada y Salida).

El sistema InSiDe es un servicio común cumple los requisitos para que documentos y expedientes puedan almacenarse y obtenerse según el ENI.

NTIs en el PAe

NTI de catálogo de estándares

NTI de documento electrónico

Metadatos mínimos obligatorios:

ID del documento

ID de la administración generadora del documento

Fecha de alta en el sistema de gestión documental

NTI de digitalización de documentos

El nivel de resolución mínimo para imágenes electrónicas será de 200 píxeles por pulgada, tanto para imágenes obtenidas en blanco y negro, color o escala de grises. Esto se define en el apartado IV.2.

Para el escaneado de documentos, la calidad mínima aceptable de la reproducción, basada en la relación del tamaño del carácter de los documentos y la resolución de captura, será de un índice de calidad (quality indicator, QI) de 3,6. Esto vino en el exámen extraordinario de 2022 del CSSTIAE. Las únicas referencias a esta calidad es en el estándar ANSI/AIIM MS23-1991, al que se hace referencia en el FIST #54-1 del NIST.

NTI de política de gestión de documentos electrónicos

La NTI de política de gestión de documentos electrónicos debe incluir al menos:

Definición del alcance y ámbito de aplicación

Actuaciones de supervisión y auditoría de los procesos de gestión de documentos

Roles de los actores involucrados

Procesos de gestión mínimos:

1. Captura
2. Registro
3. Clasificación
4. Descripción
5. Acceso
6. Calificación
7. Conservación
8. Transferencia
9. Destrucción o elminación de documentos

## Auditoría del ENI

Existe una guía de auditoría del cumplimiento del ENI.

[Guía de auditoría del cumplimiento del ENI de 2016](https://administracionelectronica.gob.es/pae_Home/dam/jcr:a859d9ac-9519-4cf9-b525-cc7238b5271b/Guia_auditoria_ENI_PDF_1ed_2016.pdf)
