# Presentación

## Estructura del ejercicio práctico

El ejercicio práctico, tal y como está planteado en la convocatoria de 2025, se compone de varias partes:

1. Supuesto práctico
2. Análisis pormenorizado
3. Volcado
4. Lectura

En esta guía se detallará cada una de ellas.

## Fecha del ejercicio práctico

La fecha exacta de realización de las partes del ejercicio práctico no son conocidas de antemano, sino que se publican a medida que avanza el proceso.

La fecha de realización del supuesto práctico y el análisis pormenorizado, compartiendo ambos convocatoria, se especifica habitualmente tras la publicación definitiva de aprobados del ejercicio precedente, que suele ser el ejercicio de test.

En la conv. 2023, la fecha definitiva del ejercicio práctico se publicó aproximadamente un mes después de haberse realizado el ejercicio de test. Desde la conv. 2022, el ejercicio práctico se realiza en viernes.

La fecha y hora de realización de la lectura es única para cada candidato. Habitualmente se realiza primero la de los candidatos de promoción interna y después la de los de ingreso libre.

En la conv. 2023, las lecturas de ingreso libre se realizaron durante tres meses y medio.

## Temas más relevantes para el ejercicio práctico

Temas más relevantes, de acuerdo a la numeración de temas de la convocatoria 2025:

- 1. Constitución Española (I)
- 2. Constitución Española (II). Poder Judicial
- 3. Constitución Española (III). Organización Territorial
- 4. Constitución Española (IV). Administración
- 5. Unión Europea
- 6. Organización territorial de la AGE
- 7. Fuentes del Derecho Administrativo
- 8. Régimen jurídico de las AAPP. Procedimiento administrativo
- 9. Revisión de los actos en vía administrativa. Recursos
- 10. La responsabilidad patrimonial de las Administraciones Públicas
- 11. Los contratos de las Administraciones Públicas
- 12. Los presupuestos generales del Estado
- 14. El modelo económico español
- 15. Los sectores de la economía
- 16. Estructura social y políticas de igualdad
- 17. El mercado de trabajo
- 18. TIC y sociedad
- 19. TIC, economía y mercado de trabajo
- 20. La función gerencial de las AAPP
- 24. Empleo Público
- 25. Gobernanza, Gobierno Abierto y Transparencia
- 27. Protección de Datos
- 39. Ley de contratos
- 44. Accesibilidad y usabilidad
- 45. ENI
- 46. NTI
- 49. Infraestructuras y servicios comunes
- 51. Agenda Digital para España. Mercado Único Digital
- 70. Inteligencia artificial
- 78. Comercio electrónico
- 80. Identificación y firma electrónica I
- 81. Identificación y firma electrónica II
- 82. Adaptación LOPD
- 89. Análisis del dominio de los sistemas
- 95. Métrica
- 99. Estimación de recursos

## Repositorio de ejercicios prácticos

El INAP recopila los enunciados de los ejercicios prácticos más recientes, mientras que Preparatic comparte los volcados de soluciones de algunos candidatos que voluntariamente los han compartido.

| Conv. | Prom. | Núm. ejer. | Título | Enun. | Volc. |
| - | - | - | - | - | - |
| 2023 | 30 | 2 | Diseño de un sistema para la gestión del ciclo presupuestario | [PDF](https://sede.inap.gob.es/documents/59312/2382235/Enunciadodelsegundoejercicio_COMPLETO_LIBRE_AA392H55BO_154AB89SD658.pdf/2e1f4267-3818-99e0-fe39-3a332520c67d) | [Drive](https://drive.google.com/drive/folders/1NRc1pcqt53SorUaOXAISC8i4LZ6Z068y?usp=sharing) |
| 2022 | 29 | 2 | Plataforma Digital Común | [PDF](https://sede.inap.gob.es/documents/59312/2298662/Enunciado2oEjercicioLibreGeneral_IX32FT6CLA_154AB89SD658.pdf/0316efec-0e7d-0c10-eaf1-cc2922e3ef85) | [Drive](https://drive.google.com/drive/folders/1opzfbqezX_lLTMW3ZArStot5yBq8aF-P?usp=sharing) |
| 2020 | 28 | 3 | Plataforma digital de cooperación entre administraciones públicas: Plataform@ | [PDF](https://sede.inap.gob.es/documents/59312/2061887/Supuestopractico3erejercicio2020_KJJ1YDZ8D2_154AB89SD658.pdf/739684b6-a1e7-e24e-ed7f-62a15a940c6a) | [Drive](https://drive.google.com/drive/folders/1wU9vF81krOYLLaC41XMCdQkcuZy_t7CF) |
| 2019 | 27 | 3 | Evolución de la Carpeta Ciudadana: Carpet@ | [PDF](https://sede.inap.gob.es/documents/59312/1863992/CSSTIAE+-+Tercer+Ej+-+Enunciado_154AB89SD658.pdf/2ed378ff-becb-b856-d64c-be7e3af3a5d9) | [Drive](https://drive.google.com/file/d/1UNqYCcdwlKYMMg5iNm3sIOOw9VzHPP_2/view) |
| 2018 | 26 | 3 | Espacio de Participación Ciudadana del Gobierno de España (ESPACE) | [PDF](https://sede.inap.gob.es/documents/59312/1763823/2019-09-14Ejercicio3_154AB89SD658.pdf/f9356500-8822-56f1-e4a3-ea20effb71b1) | - |

Adicionalmente, algunas academias y preparadores desarrollan sus propios enunciados y comparten las propuestas de solución de los candidatos.
