project:
  type: book
  output-dir: _book

book:
  title: "Ejercicio práctico del CSSTIAE 2025"
  subtitle: "Guía de preparación"
  author: "Pablo Gallardo"
  date: today
  language: es
  favicon: images/favicon.png
  
  site-url: https://pmgallardo.github.io/csstiae-2025-prac/
  repo-url: https://github.com/pmgallardo/csstiae-2025-prac
  repo-actions: [edit, issue, source]

  sidebar:
    style: "docked"
    search: true
    
  chapters:
    - index.qmd
    - part: "Presentación"
      chapters:
        - 00-presentacion/index.qmd
    - part: "Supuesto práctico"
      chapters:
        - 01-supuesto/index.qmd
        - 01-supuesto/infr-comunes.qmd
        - 01-supuesto/serv-comunes.qmd
        - 01-supuesto/modelado.qmd
        - 01-supuesto/planificacion.qmd
        - 01-supuesto/estimacion.qmd
        - 01-supuesto/contratacion.qmd
        - 01-supuesto/riesgos.qmd
    - part: "Análisis pormenorizado"
      chapters:
        - 02-analisis/index.qmd
        - 02-analisis/organismos.qmd
        - 02-analisis/regulaciones.qmd
        - 02-analisis/estrategias.qmd
        - 02-analisis/iniciativas.qmd
        - 02-analisis/transversales.qmd
        - 02-analisis/especificas.qmd
    - part: "Volcado"
      chapters:
        - 03-volcado/index.qmd
    - part: "Lectura"
      chapters:
        - 04-lectura/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
